# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

do_shrinkTVP <- function(y, x, a0, niter, nburn, nthin, c0, g0, G0, cp, np, d1, d2, e1, e2, learn_lambda2, learn_kappa2, lambda2, kappa2, learn_a_xi, learn_a_tau, a_xi, a_tau, c_tuning_par_xi, c_tuning_par_tau, b_xi, b_tau, nu_xi, nu_tau, display_progress, ret_beta_nc, store_burn, sv, Bsigma_sv, a0_sv, b0_sv, bmu, Bmu, y_test, x_test, LPDS) {
    .Call(`_shrinkTVP_do_shrinkTVP`, y, x, a0, niter, nburn, nthin, c0, g0, G0, cp, np, d1, d2, e1, e2, learn_lambda2, learn_kappa2, lambda2, kappa2, learn_a_xi, learn_a_tau, a_xi, a_tau, c_tuning_par_xi, c_tuning_par_tau, b_xi, b_tau, nu_xi, nu_tau, display_progress, ret_beta_nc, store_burn, sv, Bsigma_sv, a0_sv, b0_sv, bmu, Bmu, y_test, x_test, LPDS)
}

